adventure_works:
  outputs:
    default:
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      catalog: "{{ env_var('DATABRICKS_TARGET_CATALOG') }}"
      schema: default
      threads: 8
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: default