version: 2

sources:
  - name: HR
    database: adventure_works
    schema: human_resources
    description: "Tables Human Resources Schema"
    tables:
      - name: department
        description: "The table contains information about various departments within the organization."
        columns:
          - name: department_id
            description: "The primary key for this table."
            data_tests:
              - unique
              - not_null
      - name: employee
        description: "The table contains information about employees, including their personal details and job-related information."
        columns:
          - name: business_entity_id
            description: "The primary key for this table."
            data_tests:
              - unique
              - not_null
      - name: employee_pay_history
        description: "The table contains information about the changes on the pay for employees."
        columns:
          - name: "business_entity_id"
            description: "The first part of the primary key for this table"
            data_tests:
              - not_null
          - name: "rate_change_date"
            description: "The second part of the primary key for this table"
            data_tests:
              - not_null
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - business_entity_id
                - rate_change_date
      - name: employee_department_history
        description: "The table contains information about changes in employees department."
        columns:
          - name: business_entity_id
            description: "The first part of the primary key for this table"
            data_tests:
              - not_null
          - name: "department_id"
            description: "The second part of the primary key for this table"
            data_tests:
              - not_null
          - name: shift_id
            description: "the third part of the primary key for this table"
            data_tests:
              - not_null
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - business_entity_id
                - department_id
                - shift_id
  - name: Person
    database: adventure_works
    schema: person
    description: "Tables Person schema"
    tables:
      - name: person
        description: "This table contains detail information about our employees"
        columns:
          - name: business_entity_id
            description: "The primary key for this table"
            data_tests:
              - unique
              - not_null
      - name: address
        description: "This table contains detail information about the customer address"
        columns:
          - name: address_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: state_province
        description: "This table contains detail information about the customer state province"
        columns:
          - name: state_province_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: person_phone
        description: "This table contains detail information about person phone number"
      - name: email_address
        description: "This table contains detail information about person email address"
  - name: Sales
    database: adventure_works
    schema: sales
    description: "Sales table schema"
    tables:
      - name: sales_order_detail
        description: "This table contains detail information about our sales"
        columns:
          - name: sales_order_id
            description: "The first part of the primary key"
            data_tests:
              - not_null
          - name: sales_order_detail_id
            description: "The second part of the primary key"
            data_tests:
              - not_null
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - sales_order_id
                - sales_order_detail_id
      - name: sales_territory
        description: "This table contains detail information about the sales in a given territory "
        columns:
          - name: territory_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: sales_order_header
        description: "This table contains detail information about our transaction sales"
        columns:
          - name: sales_order_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: sales_order_header_sales_reason
        description: "This table contails the headers per the reason for the sale"
        columns:
          - name: sales_order_id
            description: "This is the first part of the primary key"
            data_tests:
              - not_null
          - name: sales_reason_id
            description: "This is the second part of the primary key"
            data_tests:
              - not_null
        data_tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - sales_order_id
                - sales_reason_id
      - name: sales_reason
        description: "This table contains the reason behind every sale"
        columns:
          - name: sales_reason_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
  - name: Production
    database: adventure_works
    schema: production
    description: "Production table schema"
    tables:
      - name: product
        description: "This table contains details about the company products they sell"
        columns:
          - name: product_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: product_subcategory
        description: "This table contains details about the product subcategories"
        columns:
          - name: product_subcategory_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
      - name: product_category
        description: "This table contains details about the product categories"
        columns:
          - name: product_category_id
            description: "This is the primary key"
            data_tests:
              - unique
              - not_null
  - name: Purchasing
    database: adventure_works
    schema: purchasing
    description: "Purchasing table schema"
    tables:
      - name: ship_method
        description: "This table contains details about the shiping method"
        columns:
          - name: ship_method_id
            description: "This is the primary key for this table"
            data_tests:
              - unique
              - not_null
